// @generated
// generated by gql

package sample

type Human struct {
	Id         string
	Name       string
	HomePlanet string
}

func (x Human) ValueFromName(name string) interface{} {
	switch name {
	case "id":
		return x.Id
	case "name":
		return x.Name
	case "homePlanet":
		return x.HomePlanet

	}
	return nil
}
