// Code generated by thriftrw
// @generated

package queryserver

import (
	"github.com/mhamrah/gql/example/starwars"
	"github.com/mhamrah/gql/example/starwars/service/query"
	"github.com/thriftrw/thriftrw-go/protocol"
	"github.com/thriftrw/thriftrw-go/wire"
	yarpc "github.com/yarpc/yarpc-go"
	"github.com/yarpc/yarpc-go/encoding/thrift"
	"golang.org/x/net/context"
)

type Interface interface {
	Droid(ctx context.Context, reqMeta yarpc.ReqMeta, request *starwars.IdRequest) (*starwars.Droid, yarpc.ResMeta, error)
	Hero(ctx context.Context, reqMeta yarpc.ReqMeta, episode starwars.Episode) (*starwars.Character, yarpc.ResMeta, error)
	Human(ctx context.Context, reqMeta yarpc.ReqMeta, request *starwars.IdRequest) (*starwars.Human, yarpc.ResMeta, error)
}

func New(impl Interface) thrift.Service {
	return service{handler{impl}}
}

type service struct{ h handler }

func (service) Name() string {
	return "Query"
}

func (service) Protocol() protocol.Protocol {
	return protocol.Binary
}

func (s service) Handlers() map[string]thrift.Handler {
	return map[string]thrift.Handler{"Droid": thrift.HandlerFunc(s.h.Droid), "Hero": thrift.HandlerFunc(s.h.Hero), "Human": thrift.HandlerFunc(s.h.Human)}
}

type handler struct{ impl Interface }

func (h handler) Droid(ctx context.Context, reqMeta yarpc.ReqMeta, body wire.Value) (thrift.Response, error) {
	var args query.DroidArgs
	if err := args.FromWire(body); err != nil {
		return thrift.Response{}, err
	}
	success, resMeta, err := h.impl.Droid(ctx, reqMeta, args.Request)
	hadError := err != nil
	result, err := query.DroidHelper.WrapResponse(success, err)
	var response thrift.Response
	if err == nil {
		response.IsApplicationError = hadError
		response.Meta = resMeta
		response.Body = result
	}
	return response, err
}

func (h handler) Hero(ctx context.Context, reqMeta yarpc.ReqMeta, body wire.Value) (thrift.Response, error) {
	var args query.HeroArgs
	if err := args.FromWire(body); err != nil {
		return thrift.Response{}, err
	}
	success, resMeta, err := h.impl.Hero(ctx, reqMeta, args.Episode)
	hadError := err != nil
	result, err := query.HeroHelper.WrapResponse(success, err)
	var response thrift.Response
	if err == nil {
		response.IsApplicationError = hadError
		response.Meta = resMeta
		response.Body = result
	}
	return response, err
}

func (h handler) Human(ctx context.Context, reqMeta yarpc.ReqMeta, body wire.Value) (thrift.Response, error) {
	var args query.HumanArgs
	if err := args.FromWire(body); err != nil {
		return thrift.Response{}, err
	}
	success, resMeta, err := h.impl.Human(ctx, reqMeta, args.Request)
	hadError := err != nil
	result, err := query.HumanHelper.WrapResponse(success, err)
	var response thrift.Response
	if err == nil {
		response.IsApplicationError = hadError
		response.Meta = resMeta
		response.Body = result
	}
	return response, err
}
