// Code generated by thriftrw
// @generated

package query

import (
	"errors"
	"fmt"
	"github.com/mhamrah/gql/example/starwars"
	"github.com/thriftrw/thriftrw-go/wire"
	"strings"
)

type DroidArgs struct {
	Request *starwars.IdRequest `json:"request,omitempty"`
}

func (v *DroidArgs) ToWire() (wire.Value, error) {
	var (
		fields [1]wire.Field
		i      int = 0
		w      wire.Value
		err    error
	)
	if v.Request != nil {
		w, err = v.Request.ToWire()
		if err != nil {
			return w, err
		}
		fields[i] = wire.Field{ID: 1, Value: w}
		i++
	}
	return wire.NewValueStruct(wire.Struct{Fields: fields[:i]}), nil
}

func _IdRequest_Read(w wire.Value) (*starwars.IdRequest, error) {
	var v starwars.IdRequest
	err := v.FromWire(w)
	return &v, err
}

func (v *DroidArgs) FromWire(w wire.Value) error {
	var err error
	for _, field := range w.GetStruct().Fields {
		switch field.ID {
		case 1:
			if field.Value.Type() == wire.TStruct {
				v.Request, err = _IdRequest_Read(field.Value)
				if err != nil {
					return err
				}
			}
		}
	}
	return nil
}

func (v *DroidArgs) String() string {
	var fields [1]string
	i := 0
	if v.Request != nil {
		fields[i] = fmt.Sprintf("Request: %v", v.Request)
		i++
	}
	return fmt.Sprintf("DroidArgs{%v}", strings.Join(fields[:i], ", "))
}

func (v *DroidArgs) MethodName() string {
	return "Droid"
}

func (v *DroidArgs) EnvelopeType() wire.EnvelopeType {
	return wire.Call
}

type DroidResult struct {
	Success *starwars.Droid `json:"success,omitempty"`
}

func (v *DroidResult) ToWire() (wire.Value, error) {
	var (
		fields [1]wire.Field
		i      int = 0
		w      wire.Value
		err    error
	)
	if v.Success != nil {
		w, err = v.Success.ToWire()
		if err != nil {
			return w, err
		}
		fields[i] = wire.Field{ID: 0, Value: w}
		i++
	}
	if i != 1 {
		return wire.Value{}, fmt.Errorf("DroidResult should have exactly one field: got %v fields", i)
	}
	return wire.NewValueStruct(wire.Struct{Fields: fields[:i]}), nil
}

func _Droid_Read(w wire.Value) (*starwars.Droid, error) {
	var v starwars.Droid
	err := v.FromWire(w)
	return &v, err
}

func (v *DroidResult) FromWire(w wire.Value) error {
	var err error
	for _, field := range w.GetStruct().Fields {
		switch field.ID {
		case 0:
			if field.Value.Type() == wire.TStruct {
				v.Success, err = _Droid_Read(field.Value)
				if err != nil {
					return err
				}
			}
		}
	}
	count := 0
	if v.Success != nil {
		count++
	}
	if count != 1 {
		return fmt.Errorf("DroidResult should have exactly one field: got %v fields", count)
	}
	return nil
}

func (v *DroidResult) String() string {
	var fields [1]string
	i := 0
	if v.Success != nil {
		fields[i] = fmt.Sprintf("Success: %v", v.Success)
		i++
	}
	return fmt.Sprintf("DroidResult{%v}", strings.Join(fields[:i], ", "))
}

func (v *DroidResult) MethodName() string {
	return "Droid"
}

func (v *DroidResult) EnvelopeType() wire.EnvelopeType {
	return wire.Reply
}

var DroidHelper = struct {
	IsException    func(error) bool
	Args           func(request *starwars.IdRequest) *DroidArgs
	WrapResponse   func(*starwars.Droid, error) (*DroidResult, error)
	UnwrapResponse func(*DroidResult) (*starwars.Droid, error)
}{}

func init() {
	DroidHelper.IsException = func(err error) bool {
		switch err.(type) {
		default:
			return false
		}
	}
	DroidHelper.Args = func(request *starwars.IdRequest) *DroidArgs {
		return &DroidArgs{Request: request}
	}
	DroidHelper.WrapResponse = func(success *starwars.Droid, err error) (*DroidResult, error) {
		if err == nil {
			return &DroidResult{Success: success}, nil
		}
		return nil, err
	}
	DroidHelper.UnwrapResponse = func(result *DroidResult) (success *starwars.Droid, err error) {
		if result.Success != nil {
			success = result.Success
			return
		}
		err = errors.New("expected a non-void result")
		return
	}
}
